### ISSUE TITLE
ionic2-date-picker directory is not present in node_modules

### ISSUE THREAD

**Issue by Simplelenz** [shangyilim/ionic2-date-picker#11]
Hello

I installed this using

`npm install ionic2-date-picker --save`

Then when I am importing it to the app.module.ts using

`import { DatePicker } from 'ionic2-date-picker/ionic2-date-picker';`

it says can't find the module. I checked whether there is any directory called ionic2-date-picker in node_modules but it is not there. Any help?

**Comment by Simplelenz** [comment]
import { DatePicker } from 'ionic2-date-picker/ionic2-date-picker';  should be 

`import { DatePicker } from 'ionic2-date-picker';

Now everything is ok. You can close this issue

**Comment by shangyilim** [comment]
thanks! I will update the readme
