### ISSUE TITLE
How to change colors?

### ISSUE THREAD

**Issue by AnandKumar2610** [shangyilim/ionic2-date-picker#13]

**Comment by shangyilim** [comment]
Hello i have updated the date picker to allow styling changes. update your date picker to the latest version
`npm install ionic2-date-picker@1.0.8`. Inside the  page you are using the date picker for example let's say `home.html`, open up the `home.scss` and add the following:

```.date-picker{
    .top-banner{
        background-color: red !important;
    }
}
```
remember to put the `!important` to

**Comment by shangyilim** [comment]
closed due to inactivity

**Comment by AnandKumar2610** [comment]
Thank you for this !!!!
