### ISSUE TITLE
Transform into component

### ISSUE THREAD

**Issue by rfoel** [shangyilim/ionic2-date-picker#14]
Wouldn't it be better if it was a component where I could use like `<date-picker></date-picker>` and be able to pass params?

**Comment by shangyilim** [comment]
Hello! Do you mind describing the usage for such a component? Usually on a mobile platform you would click on a input box and a date picker pops up, so it would be great if you could describe such use case for a component. Thanks!

**Comment by rfoel** [comment]
Let's say it's a input box for date of birth. The idea is to block all dates after today, for example. How I am using it now is to book a service, where the first valid date is tomorrow. In this case I block all dates before or same today. I do it like this `momentDate.isSameOrBefore(moment().startOf("day"))`, if it returns true it disables the date.

**Comment by shangyilim** [comment]
so you would need something like this?
```
<date-picker [startDate]="startDate" [endDate]="endDate"></date-picker>
```
When this is added to any html, what do you see? the entire rendered calendar with the dates greyed out?

**Comment by rfoel** [comment]
Yes. Basically the dates will be greyed out if they are not in the range. For a better user experience I would suggest block the years/months where there are no enabled dates. And further than start and end dates, I would add a array with disabled dates as well, so the user will be able to disable certain dates as well.

`<date-picker [disabledDates]="disabledDates"></date-picker>`
