### ISSUE TITLE
ios build --prod gives error

### ISSUE THREAD

**Issue by Simplelenz** [shangyilim/ionic2-date-picker#17]
When I run the following command in my project where I have used the ionic2-date-picker I am getting an error.

Command to build to ios
`ionic cordova build ios --prod`

Error:

> [WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova).
Error: Unexpected value 'DatePicker in /Users/tharindu/Downloads/Projects/mastersLoyalty/node_modules/ionic2-date-picker/date-picker.component.d.ts' declared by the module 'AppModule in/Users/tharindu/Downloads/Projects/mastersLoyalty/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

**Comment by gvishwanath** [comment]
I'm also getting same issue.

**Comment by Simplelenz** [comment]
Let me know if you have found a solution for this

**Comment by gvishwanath** [comment]
I got the solution now. Have a look below steps.

Step 1 - Download and extract this component. 
Step 2 - Rename the lib folder to ionic2-date-picker.
Step 3 - Copy and Paste the renamed folder to your ionic app component folder. 
Step 2 - Now this component you can use like local component 
              EX: import { DatePicker } from '../../components/ionic2-date-picker/date-picker.component';

Remaining code as same.

**Comment by Simplelenz** [comment]
Thanks I will try this

**Comment by Simplelenz** [comment]
When I try your method I am getting the following error.

> GET http://localhost:8100/date-picker.scss 404 (Not Found)

> Unhandled Promise rejection: Failed to load date-picker.scss ; Zone: <root> ; Task: Promise.then ; Value: Failed to load date-picker.scss undefined

Any help on this?

**Comment by Simplelenz** [comment]
Got this to work.

```
@Component({
  selector: 'date-picker',
  templateUrl: 'date-picker.html',
  // styleUrls: ['date-picker.scss'],
})
```

in the date-picker.component.ts I had to remove the "styleUrls. That fixed the issue

**Comment by thesurya9** [comment]
Same issue ionic cordova build android --prod --release please help ?

**Comment by thesurya9** [comment]
@gvishwanath  does your solution works for android?

**Comment by Simplelenz** [comment]
Hi thesurya9,

Above solution works in android and it will stop giving the build error for ios. But when you test it on the ios device,  the date picker will not popup. But it works fine in android device

**Comment by thesurya9** [comment]
@Simplelenz  okay let me try . Thanks for your time :)

**Comment by thesurya9** [comment]
@Simplelenz Thnaks bro .. works for. U r life saver (y)

**Comment by Simplelenz** [comment]
@thesurya9 

Does it work in iOS device too?

**Comment by thesurya9** [comment]
@Simplelenz  haven't tested on ios. only made an android build. yes, it is working fine on Android.

**Comment by shangyilim** [comment]
Hi guys, i have fixed the AOT issue with ionic. Unfortunately it will introduce breaking changes.
Please update to `ionic2-date-picker@1.1.0` to  get the AOT workable version.

Thanks!
