### ISSUE TITLE
Two Date picker on same page 

### ISSUE THREAD

**Issue by thesurya9** [shangyilim/ionic2-date-picker#18]
I have two input filed on the same page. I have to use same date picker on both of the places. 
please tell me how can I do it? 
anyhow I m doing this but both of the filed change to same value.

**Comment by shangyilim** [comment]
Hello! can you check whether your problem can be solved with this solution ? https://github.com/shangyilim/ionic2-date-picker/issues/4

Thanks!

**Comment by thesurya9** [comment]
Yes, now it's working fine. Thank you so much. 
I just need to one more thing. 
• I want to open calendar when the user clicks on Input filed, at the same time keyboard should not be on.

here is my code . 

<ion-item >
        <ion-label style="color: #027CD3;">
          <ion-icon  name="calendar" > </ion-icon> Start Date( dd/mm/yy) </ion-label>
        <ion-input  type="text" (focus)="showCalendar()" formControlName="startdate" name="startdate"></ion-input>
      </ion-item> 

is showing keyboard for a second and then calendar popups. 
could you please help me out ?

**Comment by nikmartin** [comment]
@thesurya9 if the filed should only be populated by the datePicker, then you can set the input to disabled and use the (tap)="showCalendar()" event and you should get a better experience

**Comment by thesurya9** [comment]
@nikmartin Thanks, man. That solves my problem.

**Comment by thesurya9** [comment]
@shangyilim please help me one more time. thank you in advance. 
Q-  Can I stop the user from selecting weekdays?
like he cannot select Saturday or Sunday?

**Comment by shangyilim** [comment]
@thesurya9 the datepicker doesnt have the functionality to disable days. But what you can do now at the moment is that once the date value is returned, you can check whether it is on weekends, and ignore the value.
