### ISSUE TITLE
Can I disable future date, same as I am disabling past date. 

### ISSUE THREAD

**Issue by thesurya9** [shangyilim/ionic2-date-picker#24]
hey.. You made update for disabling past date by adding 
`let datePickerOption: DatePickerOption = {
      minimumDate: new Date() // the minimum date selectable
};`
first of all thank u so much for this. 

**Now I need to disable future date.. like am using it on date of birth field .. DOB can not be future date so could you provide the option for maximum date ?**

please help. 
Thank You in advance

**Comment by thesurya9** [comment]
Can someone please help me out?

**Comment by shangyilim** [comment]
i will get this feature implemented

**Comment by shangyilim** [comment]
take a look at `ionic2-date-picker@1.0.11`
