### ISSUE TITLE
Two inputs value cannot be distinct

### ISSUE THREAD

**Issue by sujiththakur** [shangyilim/ionic2-date-picker#4]
If I have 2 input fields in the same page, the values cannot be unique? Its replacing the 1st input field value when the 2nd input field is selected from the calendar.

**Comment by shangyilim** [comment]
thats weird, but i'll check it out soonest

**Comment by sujiththakur** [comment]
Any improvements in this issue?

**Comment by shangyilim** [comment]
Hello, I'm working on this as well thanks!

**Comment by shangyilim** [comment]
Hello, update to latest package `npm install ionic2-date-picker@1.0.7`, and you should be able to create multiple date pickers for each field you want like so:
```
private datePicker: DatePicker;
  private datePicker2: DatePicker;

  constructor(public navCtrl: NavController,
    public modalCtrl: ModalController,
    public viewController: ViewController) {

    this.datePicker = new DatePicker(<any>this.modalCtrl, <any>this.viewController);
    this.datePicker.onDateSelected.subscribe((date) => { console.log(date); });

    this.datePicker2 = new DatePicker(<any>this.modalCtrl, <any>this.viewController);
    this.datePicker2.onDateSelected.subscribe((date) => { console.log(date); });
  }

  showCalendar() {
    this.datePicker.showCalendar();
  }
  showCalendar2() {
    this.datePicker2.showCalendar();
  }
```

**Comment by sujiththakur** [comment]
Hi, Will this work in Ionic 3 as well? Because after I updated your module, Its saying module not found.

**Comment by shangyilim** [comment]
I tested with latest ionic. Can you post the exact version of ionic are u
using

**Comment by sujiththakur** [comment]
Hi, Sorry , I had tested it wrong. Its working fine. Thank you so much. Just one thing though Can i get the output for only the date instead of day and time , I want it in 'Sep 07 2017' format ?

**Comment by sujiththakur** [comment]
I figured it out using Datepipe. Thanks a lot for these changes. Have a nice day.

**Comment by shangyilim** [comment]
Glad to hear! closing this issue.
