### ISSUE TITLE
How to set my customized date as default date of Date Picker ???

### ISSUE THREAD

**Issue by thurimerla** [shangyilim/ionic2-date-picker#40]
Hi @shangyilim ,

I'm trying to set my customized date as a default date of DatePicker.
I'm confusing where I have to change the code to set default date.

Please help me.

**Comment by thurimerla** [comment]
Hi @shangyilim ,

I would like to pass dynamically date from my web page script file to **setTodayAsDefaultSelectedDate( )** function.

This is appeared in **ionic2-date-picker\src-inlined\components\date-picker\date-picker.js**.

So please guide me how to change DatePicker default dynamically.

**Comment by thurimerla** [comment]
Hi @Bastl34  and @shangyilim , 

I would like to ask you regarding this issue, Do you have any idea to resolve my issue or not ??

If not means please tell me and please don't stay in silent mode.

If you give reply I am very thankful  to you @Bastl34 and @shangyilim .

**Comment by Bastl34** [comment]
Sorry I have no idea.
I'm currently not in to this and this.
If you have issues with the current state you can fork this repo and fix it by yourself.

**Comment by shangyilim** [comment]
@Bastl34  thanks for helping out! 👍 

@thurimerla I have added a `defaultDate` option please update to latest version @1.1.3 . If you are not sure how to use it, please refer to the README.md
