### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mvaipa** [shangyilim/ionic2-date-picker#6]
I'm having the following error, could you help me

$ ionic cordova build android --prod
Running app-scripts build: --build --prod --iscordovaserve --nobrowser

[10:38:46]  build prod started ...
[10:38:46]  clean started ...
[10:38:46]  clean finished in 6 ms
[10:38:46]  copy started ...
[10:38:46]  ngc started ...
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova).
Error: Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in C:/sistema/ummedicobomionic/trunk/node_modules/ionic2-date-picker/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in C:/sistema/ummedicobomionic/trunk/node_modules/ionic2-date-picker/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in C:/sistema/ummedicobomionic/trunk/node_modules/ionic2-date-picker/node_modules/@angular/core/src/di/opaque_token.d.ts

**Comment by gerardob** [comment]
I have the same error, how you fix it? or need a plugin modification?? I cannot build with --prod flag

**Comment by shangyilim** [comment]
Hello, i'll take a look  as soon as possible over the weekends :)

**Comment by mvaipa** [comment]
The solution I had was to create a new screen, and copy css, javascript and html, direct and remove the plugin, it ran right with some adaptations ...

**Comment by shangyilim** [comment]
can you try upgrading your version of the library?

**Comment by shangyilim** [comment]
closed due to inactivity.
