### ISSUE TITLE
showCalendar() not rendering proper display

### ISSUE THREAD

**Issue by kirstenfrager** [shangyilim/ionic2-date-picker#9]
I have followed the exact installation instructions and code placement as in the ReadMe but am getting the below view of the calendar when I click to open.

Can someone please help as to why this is happening?

![screen shot 2017-08-15 at 10 10 54 am](https://user-images.githubusercontent.com/21212453/29297151-48f89daa-81a2-11e7-9a0c-277ecdcb11db.png)

There are no errors in the console. But have found this in my terminal output if this may have any relation?

[Error - 10:10:04 AM] Notification handler 'textDocument/didSave' failed with message: DatePicker cannot be used as an entry component.

**Comment by KKeertikeya** [comment]
I have the same issue. Please keep posted about the fix

**Comment by RodrigoRMG** [comment]
Same problem here

**Comment by shangyilim** [comment]
Please try with the latest version of the plugin.
`npm install ionic2-date-picker@1.0.7`
